insurance_csv: "data/input/exp/Motor_vehicle_insurance_data.csv"

features:
  - Area
  - Type_risk
  - Value_vehicle
  - fuel_type_encoded
  - Cylinder_capacity
  - Year_matriculation
  - Distribution_channel
  - driver_experience_age
  - Value_vehicle_log_transformed
  - driver_age_experience_age_diff
  - driver_age_at_contract_inception
  - driver_age_experience_ratio_proxy_for_driving_experience

target: N_claims_year

frequency:
  algorithm: poisson_regressor
  parameters:
    alpha: 1.0
    max_iter: 1000

tracking:
  uri: "http://127.0.0.1:5000"
  experiment_name: "Insurance Claims Frequency Model"
  run_name: "run_005"
  run_description: "Poisson regression for insurance claims frequency prediction"
  artifact_model_name: "poisson_model"